name: Update NasaPhone Repo (Universal Release)

on:
  workflow_dispatch: # تشغيل يدوي من تبويب Actions

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ضروري لمنح البوت صلاحية إنشاء الـ Release
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Universal APK
        run: |
          # تحميل الملف وتسميته باسم عام ليشمل كل المعالجات
          wget -O ABWhatsApp_Blue_v30.apk "https://download1507.mediafire.com/jnebkx5zubcgFd4d9WcpJvaUyk9EYk8z1TlHmiUeuqSolDqQKfRR3G6WjYKNOy1B7kTSdcGHaZu5qlXTgpoinuS4NnWSVsQHB3MZZpvSuq1cvQXURejSUVCyZlPG_eIyX4r8_obH3BhVWcTPYkvpRjkjJAetiLA0evDaIOqr_P58XIw/cj97u5khag81kjc/ABWhatsApp_Blue_v30.apk"

      - name: Run Generate Script
        run: |
          # تأكد من وجود ملف generate.sh في المجلد الرئيسي
          chmod +x generate.sh
          ./generate.sh

      - name: Sign Index Jar
        run: |
          # تأكد من وجود ملف nasa_new.jks في المجلد الرئيسي
          zip index-v1.jar index-v1.json
          jarsigner -keystore nasa_new.jks -storepass nasaphone123 -keypass nasaphone123 index-v1.jar nasa_alias

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v30
          name: "NasaPhone Universal v30"
          draft: false
          prerelease: false
          files: |
            ABWhatsApp_Blue_v30.apk
            index-v1.jar
            index-v1.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
